### PR TITLE
New Feature: Profile Edit

### PR DESCRIPTION
**Pull request by TaninDean**
workflow
[codecov](https://codecov.io/gh/ThaiRepose/thairepose)

### What is the feature?
Profile/ Profile-edit:
 * User can visit there profile.
 * User can edit profile and imageprofile.
### What is the solution?
Create form to make profile can editable.
### How to test?
Manual by hand.
### Other Notes
Before teser test it. You need to create new accout before test.
Html for test:
 * profile/
 * editprofile/
### Screen shot
สกรีนช็อต 2021-11-20 121719
สกรีนช็อต 2021-11-20 121746
สกรีนช็อต 2021-11-16 14
4746

### CODE REVIEW

**Comment by nabhan-au** [comment]
why you push profile picture to github?

**Comment by nabhan-au** [comment]
image
when using small size screen user can't change their picture

**Comment by nabhan-au** [comment]
When user change their profile picture. It should remove old profile picture and save it in the same name as old picture

**Comment by TaninDean** [comment]
i have fix it already. Please check it again.

**Comment by nabhan-au** [comment]
image
when name is too long it broke the layout and the profile picture still don't delete

**Comment by nabhan-au** [comment]
Now every user that changes profile picture. They use same profile picture because it save in the same name

**Comment by nabhan-au** [comment]
image
 When I change profile picture second time i cause this bug

**Comment by TaninDean** [comment]
i recommend you to delete databae because i have chage core of function.

**Comment by nabhan-au** [comment]
name and surname should be in the same line and don't forget to make sure that all test pass

**Comment by nabhan-au** [comment]
I think profile picture path shouldn't show to user

**Comment by nabhan-au** [comment]
image

**Review by nabhan-au — APPROVED** [review]
Nice work

**Pull request merged**
