### PR TITLE
New Feature Completed: Trip Organizer

### PR DESCRIPTION
**Pull request by tboonma**
workflow codecov

### What is the feature?
Trip Organizer that can let user pick some places desired to be in the trip. And then calculate the time table for their trip. To help user organize their trip easier. The schedule also has auto-save function to keep the table existed for owner user.
### What is the solution?
- Separate `Planner` app from `Trip`
- Getting directions API
- Store time table in the database (Directions time not included.)
### How to test?
 - Login and go to `Planner` tab in the navigation bar, try to using all functions.
### Screen shot
Screen Shot 2564-11-21 at 18 30 07
Screen Shot 2564-11-21 at 18 28 32
Screen Shot 2564-11-21 at 18 28 20
Screen Shot 2564-11-21 at 18 30 12
Screen Shot 2564-11-21 at 18 28 14

### CODE REVIEW

**Comment by vitvara** [comment]
I can't calculate time.
Error message 
Terminal
image

Console
image

**Comment by tboonma** [comment]
> I can't calculate time. Error message Terminal image
> 
> Console image

Thank you. I'll fix it ASAP.

**Comment by tboonma** [comment]
Fixed, please try again.

**Comment by vitvara** [comment]
image
When i change depart time it change back to previous time.

**Review by vitvara — APPROVED** [review]
👍👍👍👍👍👍👍

**Pull request merged**
