### PR TITLE
UI Improvement: Added TailwindCSS to some page.

### PR DESCRIPTION
**Pull request by tboonma**
### What is the feature?
- Improved UI for these pages:
  - account_inactivate.html
  - signup_close.html
### Screen shot
Screen Shot 2564-11-06 at 16 23 57
Screen Shot 2564-11-06 at 16 25 25

### CODE REVIEW

**Comment by nabhan-au** [comment]
image
Do you forget to commit your url file?

**Comment by nabhan-au** [comment]
image
What happen with picture

**Comment by tboonma** [comment]
OK. I committed them.

**Review by nabhan-au — APPROVED** [review]
Nice work

**Pull request merged**
