### PR TITLE
New authentication with Oauth

### PR DESCRIPTION
**Pull request by nabhan-au**
[Build Status](https://app.travis-ci.com/ThaiRepose/thairepose)
[codecov](https://codecov.io/gh/ThaiRepose/thairepose)
### Feature
- Login-Logout by using django-allauth
- Email verification by using django-allauth
- Google Oauth by using django-allauth
- Create profile with picture

### Solution
- Create Extended user model name Profile
- Create adapter.py for edit save_user() to save information to profile model
- Add upload_profile_pic function for add profile picture path to profile model and save picture in directory
- Add template folder(templates/account/) that come with library for edit page that involve with authentication

### How to test?
For Oauth and sign up with library. You should test by follow readme and runserver. And test by try to sign up with both way
### Other Notes
**url path**
- signup: accounts/signup
- login: accounts/login
- logout: accounts/logout
### Screen shot
image
image
image
image
image

### CODE REVIEW

**Comment by TaninDean** [comment]
why I test it by any email it has an error  !!!
Screen Shot 2564-10-29 at 23 57 19

**Comment by TaninDean** [comment]
and you need to resolve conflicts

**Comment by nabhan-au** [comment]
It may be happen because you type in wrong email or password
And if you use Mac. it may happen when you use os.environ.get().

**Comment by TaninDean** [comment]
Oh i see. Then you should include a notice in the readme to warn users who are having the same issue as me.

**Comment by TaninDean** [comment]
Other thing is good. Nice work krub.

**Review by TaninDean — APPROVED** [review]

**Pull request merged**
