### PR TITLE
Login register page.

### PR DESCRIPTION
**Pull request by TaninDean**
[Build Status](https://app.travis-ci.com/ThaiRepose/thairepose) [codecov](https://codecov.io/gh/ThaiRepose/thairepose)
### What is the feature?
 * Add tailwind css to login and register page
### How to test?
 * Test by manual access to feature link in each page.
### Screen shot
สกรีนช็อต 2021-11-07 153036
สกรีนช็อต 2021-11-07 153055

### CODE REVIEW

**Comment by nabhan-au** [comment]
image
image
why color is difference

**Comment by TaninDean** [comment]
I not sure why but I have same issue before I think you need tailwind build and install then start again

**Comment by nabhan-au** [comment]
I think when user go to login page it shouldn't have alert message pop up

**Review by nabhan-au — APPROVED** [review]
Nice work

**Pull request merged**
